### ISSUE TITLE
can we get the ipv6 information in the show action?

### ISSUE THREAD

**Issue by digitalsushi** [linode/cli#14]
Thanks for adding the json output!  It's great!

Could we get the IPv6 address(es) and netmasks in the 'show' action?

We would also like to learn the mac address of the interfaces with this tool, but that's probably not going to be very popular.  

I think the IPv6 stuff would be useful for everyone.

**Comment by willemdh** [comment]
Any news about this? I found no way to get the ipv6 address of a newly created linode... Ideally the ipv6 address should be shown, just like the ipv4 address, by default the moment the linode is created.

**Comment by displague** [comment]
Thanks, @digitalsushi @willemdh

This cli is deprecated in favor of https://github.com/linode/linode-cli which offers a `linode-cli linodes list --all` command that does include the IPv6 address of the Linode instance.

`pip install linode-cli`

See https://github.com/linode/linode-cli/issues/48 also.
