### ISSUE TITLE
`linode configure` should use readline for text entry

### ISSUE THREAD

**Issue by doherty** [linode/cli#20]
```
Path to an SSH public key to install when deploying a new Linode. (Optional)
>> /homem^H/^H^H^H
```

That's just annoying :(

**Comment by eatonphil** [comment]
As a quick solution, you may be able to use [rlwrap](https://github.com/hanslub42/rlwrap) to give the cli readline capabilities. (It is available in the debian/ubuntu and os x package managers and probably most others.)

You could add this to your ~/.profile to give it a try:

```
alias linode='rlwrap linode -P full'
```

**Comment by displague** [comment]
Thanks for reporting this @doherty and for the solution @eatonphil .

This API v3 based CLI is deprecated in favor of the Linode API v4 based CLI at https://www.github.com/linode/linode-cli (`pip install linode-cli`).

While `linode-cli configure` may not include tab completion, none of the questions in the new linode-cli would use tab completion.  The current configuration questions are:

1. Personal Access Token
2. Default Region (choose from list - 1-9)
3. Default Type (choose from list - 1-15)
4. Default Image (choose from list - 1-20)

`rlwrap` would still work if there were a question that involved a path.
