### ISSUE TITLE
linode nodebalancer config-create fails complaining about bad ssl-cert

### ISSUE THREAD

**Issue by zachsnow** [linode/cli#25]
Attempting to create an SSL-terminating configuration fails:
```
$ linode nodebalancer config-create --protocol="https" \
  --label="staging" --port="443" --ssl-cert="..." --ssl-key="..." \
  --check-health="http" --check-interval="60" \
  --check-timeout="30" --check-attempts="4" --check-path="/version/"
Unable to create NodeBalancer config for staging. API Error 8: SSL private key appears to be incorrectly formatted
```
(Obviously `--ssl-cert` and `--ssl-key` have real values, which I checked with `openssl -check`; they do contain newlines, not sure if that's an issue despite being quoted).

Creating the configuration by hand in the Lindode Manager by pasting the exact same certificate and key (used `cat key | pbcopy`) worked fine. I imagine I'm somehow not constructing my command correctly but the documentation doesn't say anything about the required format.

**Comment by jamesottinger** [comment]
Zach, thank you for opening this issue.  The latest release allows you to specify a file, which is a solution to this problem. Cheers!
