### ISSUE TITLE
Do not try to create .linodecli dir if not necessary

### ISSUE THREAD

**Issue by liayn** [linode/cli#27]
We're using the linode domain cli tools in web-scripts. The scripts are run as a user with very limited permissions. The user is NOT allowed to create the .linodecli directory in the home directory.

Since the API key is specified via command line arguments, the directory is not necessary at all.
If we remove the mkdir() command from Util.pm::check_configs(), the scripts work without problems.

Would it be possible to add a check that skips the creation of this directory when not needed?

Thanks.

**Comment by jamesottinger** [comment]
liayn, thank you again for reporting this issue.
The latest release addresses this and doesn't require a .linodecli dir or config.

**Comment by liayn** [comment]
@jamesottinger Awesome! Waiting for the update to hit the repository.
