### ISSUE TITLE
The perl problem persist.

### ISSUE THREAD

**Issue by acald3ron** [linode/cli#28]
I have a i386 kernel  and i have thist problem:

acald3ron@stark:~$ uname -a
Linux stark 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) i686 GNU/Linux

acald3ron@stark:~$ linode configure
Can't locate Linode/CLI/Util.pm in @INC (you may need to install the Linode::CLI::Util module) (@INC contains: /usr/bin/lib /etc/perl /usr/local/lib/i386-linux-gnu/perl/5.20.1 /usr/local/share/perl/5.20.1 /usr/lib/i386-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/i386-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /usr/bin/linode line 14.
BEGIN failed--compilation aborted at /usr/bin/linode line 14.

more info:

 dpkg -L linode-cli
/.
/usr
/usr/bin
/usr/bin/linode
/usr/bin/linode-account
/usr/bin/linode-domain
/usr/bin/linode-linode
/usr/bin/linode-nodebalancer
/usr/bin/linode-stackscript
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/perl5
/usr/lib/x86_64-linux-gnu/perl5/5.20
/usr/lib/x86_64-linux-gnu/perl5/5.20/Linode
/usr/lib/x86_64-linux-gnu/perl5/5.20/Linode/CLI.pm
/usr/lib/x86_64-linux-gnu/perl5/5.20/Linode/CLI
/usr/lib/x86_64-linux-gnu/perl5/5.20/Linode/CLI/Object.pm
/usr/lib/x86_64-linux-gnu/perl5/5.20/Linode/CLI/Object
/usr/lib/x86_64-linux-gnu/perl5/5.20/Linode/CLI/Object/Account.pm
/usr/lib/x86_64-linux-gnu/perl5/5.20/Linode/CLI/Object/Linode.pm
/usr/lib/x86_64-linux-gnu/perl5/5.20/Linode/CLI/Object/Stackscript.pm
/usr/lib/x86_64-linux-gnu/perl5/5.20/Linode/CLI/Object/Domain.pm
/usr/lib/x86_64-linux-gnu/perl5/5.20/Linode/CLI/Object/Nodebalancer.pm
/usr/lib/x86_64-linux-gnu/perl5/5.20/Linode/CLI/Util.pm
/usr/lib/x86_64-linux-gnu/perl5/5.20/Linode/CLI/SystemInfo.pm
/usr/lib/x86_64-linux-gnu/perl5/5.20/WebService
/usr/lib/x86_64-linux-gnu/perl5/5.20/WebService/Linode.pm
/usr/lib/x86_64-linux-gnu/perl5/5.20/WebService/Linode
/usr/lib/x86_64-linux-gnu/perl5/5.20/WebService/Linode/Base.pm
/usr/lib/x86_64-linux-gnu/perl5/5.20/WebService/Linode/DNS.pm
/usr/share
/usr/share/doc
/usr/share/doc/linode-cli
/usr/share/doc/linode-cli/copyright
/usr/share/doc/linode-cli/changelog.Debian.gz
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/linode-domain.1.gz
/usr/share/man/man1/linode-linode.1.gz
/usr/share/man/man1/linode-stackscript.1.gz
/usr/share/man/man1/linode.1.gz
/usr/share/man/man1/linode-account.1.gz
/usr/share/man/man1/linode-nodebalancer.1.gz

i dont want to used multi-arch !

**Comment by jamesottinger** [comment]
We have pushed a new package which addresses this/your issue.  Let me know if you have any problems. Thanks!
