### ISSUE TITLE
[Suggestion] 'linode domain record-list' should show TTL

### ISSUE THREAD

**Issue by PHLAK** [linode/cli#29]
**Current:**

    $ linode domain record-list --label example.com
    Domain records for example.com
    + -------- + ------------------------ + -------------------------------- + -------- +
    | type     | name                     | target                           | port     |
    | -------- + ------------------------ + -------------------------------- + -------- |
    | A        |                          | 1.2.3.4                          | 80       |
    | A        | www                      | 1.2.3.4                          | 80       |
    | CNAME    | bar                      | 1.3.5.7                          | 80       |
    | CNAME    | baz                      | 2.4.6.8                          | 80       |
    + -------- + ------------------------ + -------------------------------- + -------- +

**Suggestion:**

    $ linode domain record-list --label example.com
    Domain records for example.com
    + -------- + ------------------------ + -------------------------------- + -------- + -------- +
    | type     | name                     | target                           | port     | ttl      |
    | -------- + ------------------------ + -------------------------------- + -------- + -------- +
    | A        |                          | 1.2.3.4                          | 80       | 1800     |
    | A        | www                      | 1.2.3.4                          | 80       | 1800     |
    | CNAME    | bar                      | 1.3.5.7                          | 80       | 300      |
    | CNAME    | baz                      | 2.4.6.8                          | 80       | 3600     |
    + -------- + ------------------------ + -------------------------------- + -------- + -------- +

**Comment by jamesottinger** [comment]
Great suggestion, thanks!

**Comment by jamesottinger** [comment]
We will be including your request in an update sometime early next week. Thank you once again for your suggestion!
