### ISSUE TITLE
The value of balance is a minus one.

### ISSUE THREAD

**Issue by samurai00** [linode/cli#30]
```
> linode account show
          managed: no
          balance: $ -29.91
    transfer pool: 3000.00GB
    transfer used: 7.00GB
transfer billable: 0.00GB
   billing method: metered

> linode --version
linode-cli 1.4.5
Copyright (C) 2015 Linode, LLC
```
In Linode Manager
```
Account Balance     $29.91 credit
Uninvoiced Balance  $3.75 and counting
```

**Comment by jamesottinger** [comment]
Hi samurai00,

The reason that it shows your balance as a negative is that you have a credit of $29.91 on your account.  So you owe $-29.91. The api (account.info) spits it out raw and that is also how the CLI currently displays it.  For the "show" I think we could make it clearer on the CLI side to better match the manager. I'm going to adjust the CLI to show that it is a credit in those cases. Thanks for reporting this!
