### ISSUE TITLE
image-list failing with Generic error

### ISSUE THREAD

**Issue by cmawhorter** [linode/cli#32]
`linode image-list` failing. linode-cli v1.4.6 yosemite.   curl works.

```
$ LINODE_API_KEY=... linode image-list --json
Can't call image_list at /usr/local/Cellar/linode-cli/1.4.6/lib/perl5/site_perl/Linode/CLI/Object/Linode.pm line 1093.
{
   "Generic error" : {
      "request_action" : "",
      "request_error" : "Problem while trying to run 'linode image-list'"
   }
}
```

**Comment by jamesottinger** [comment]
This works for me, but I'm using my account. I tested against Perl 5.16.2 and Perl 5.18.2.  Could you provide the version of Perl you have and anything else what may help me duplicate the issue?
Thank you for reporting your issue and helping!

**Comment by cmawhorter** [comment]
Perl v5.18.2.  "This is perl 5, version 18, subversion 2 (v5.18.2) built for darwin-thread-multi-2level"

Yeah, don't know.  Tried on a newer computer that has less customization and still same issue.  (Also errors without json in case that helps.)  

I noticed a debug arg in the source but don't think I'm passing it correctly.  Happy to dig more if you want.

It's not a huge deal for me personally since curl'ing the api directly works.  Feel free to close if you want.  Thanks!

**Comment by jamesottinger** [comment]
Thank you for providing more information!  Hum..., I am using the same exact Perl version on Mac that you are. I would really like to get to the bottom of it and appreciate your help.  Would you be willing to open a support ticket on the account that is experiencing the issue?

**Comment by jamesottinger** [comment]
The issue turned out to be in the homebrew-cli formula, which was patched today. If you run "brew reinstall linode/cli/linode-cli" your issue should get resolved. Thank you for your help! Your Linode ticket was updated and we put a thank you in there for you.  :)
