### ISSUE TITLE
update for Debian 9 (stretch) i386

### ISSUE THREAD

**Issue by acald3ron** [linode/cli#34]
Im a Debian testing user for arch 386 and theres no package:

sudo bash -c 'echo "deb http://apt.linode.com/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/linode.list'
[sudo] password for acald3ron: 
acald3ron@stark:~$ wget -O- https://apt.linode.com/linode.gpg | sudo apt-key add -
--2015-06-20 13:31:02--  https://apt.linode.com/linode.gpg
Resolving apt.linode.com (apt.linode.com)... 97.107.139.216, 2600:3c03::f03c:91ff:fe70:738c
Connecting to apt.linode.com (apt.linode.com)|97.107.139.216|:443... connected.
GnuTLS: A TLS warning alert has been received.
GnuTLS: received alert [112]: The server name sent was not recognized
HTTP request sent, awaiting response... 200 OK
Length: 1133 (1.1K)
Saving to: ‘STDOUT’

-                     100%[==========================>]   1.11K  --.-KB/s   in 0s     

2015-06-20 13:31:03 (4.77 MB/s) - written to stdout [1133/1133]

OK
acald3ron@stark:~$ sudo apt-get update
Ign http://dl.google.com stable InRelease
Ign http://apt.linode.com stretch InRelease                                           
Hit http://dl.google.com stable Release.gpg                                           
Hit http://security.debian.org testing/updates InRelease                              
Hit http://dl.google.com stable Release                                               
Ign http://apt.linode.com stretch Release.gpg                        
Hit http://mirrors.linode.com testing InRelease                         
Ign http://apt.linode.com stretch Release                               
Hit http://security.debian.org testing/updates/main Sources                           
Hit http://dl.google.com stable/main i386 Packages                                    
Hit http://security.debian.org testing/updates/main i386 Packages                     
Get:1 http://mirrors.linode.com testing/main Sources/DiffIndex [7,876 B]              
Hit http://security.debian.org testing/updates/main Translation-en                    
Get:2 http://mirrors.linode.com testing/contrib Sources/DiffIndex [3,541 B]
Get:3 http://mirrors.linode.com testing/non-free Sources/DiffIndex [3,541 B]   
Get:4 http://mirrors.linode.com testing/main i386 Packages/DiffIndex [7,876 B] 
Get:5 http://mirrors.linode.com testing/contrib i386 Packages/DiffIndex [4,645 B]
Get:6 http://mirrors.linode.com testing/non-free i386 Packages/DiffIndex [3,541 B]
Get:7 http://mirrors.linode.com testing/contrib Translation-en/DiffIndex [2,161 B]
Get:8 http://mirrors.linode.com testing/main Translation-en/DiffIndex [7,876 B]
Get:9 http://mirrors.linode.com testing/non-free Translation-en/DiffIndex [2,023 B]
Ign http://dl.google.com stable/main Translation-en_US                                
Ign http://dl.google.com stable/main Translation-en                                   
Err http://apt.linode.com stretch/main i386 Packages                                  
  404  Not Found [IP: 97.107.139.216 80]
Ign http://apt.linode.com stretch/main Translation-en_US                              
Ign http://apt.linode.com stretch/main Translation-en                                 
Fetched 43.1 kB in 7s (5,446 B/s)                                                     
W: Failed to fetch http://apt.linode.com/dists/stretch/main/binary-i386/Packages  404  Not Found [IP: 97.107.139.216 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by jamesottinger** [comment]
Hi acald3ron,

I pushed out a build for "stretch" on apt.linode.com. You should be good-to-go. Thank you for opening the issue!

**Comment by jamesottinger** [comment]
Build pushed.

**Comment by acald3ron** [comment]
thanks !
