### ISSUE TITLE
Failed to update tap: linode/cli

### ISSUE THREAD

**Issue by nntoan** [linode/cli#35]
Hello,

On a beautiful afternoon, I ran this command `brew update` and got this:

```bash
Error: Failed to update tap: linode/cli
```

What had happened?

**Comment by ravenx99** [comment]
brew failed to update the tap "linode/cli". :)

With no other information, I'd guess it failed in contacting github.  In any case, this shouldn't be a problem with the repository itself.

What's the output of "brew info linode-cli"?  Should show current stable is 1.4.6.

Do you get that error every time you run "brew update"?

**Comment by jamesottinger** [comment]
nntoan,

What happens when you run "brew update linode-cli"?

**Comment by nntoan** [comment]
Thank guys, I think my issue has been solved.

The trouble come from /usr/local/ permission.
