### ISSUE TITLE
Missing Linode.Disk API options 

### ISSUE THREAD

**Issue by stevesmename** [linode/cli#36]
It appears that there isn't many options to create and manage disks as stated in the API documentation. https://www.linode.com/api/linode

**Comment by displague** [comment]
Thanks for reporting this @stevesmename.

This CLI is deprecated in favor of https://www.github.com/linode/linode-cli (`pip install linode-cli`) which is based on v4 of the Linode API, affording more features and flexibility.

A number of disk related commands are available in the new CLI:
```
$ linode-cli linodes | grep disk
│ disks-list          │ List Disks                   │
│ disk-create         │ Create Disk                  │
│ disk-view           │ View Disk                    │
│ disk-update         │ Update Disk                  │
│ disk-delete         │ Delete Disk                  │
│ disk-reset-password │ Reset Disk Root Password     │
│ disk-resize         │ Resize Disk                  │
```

You can inspect the options of each command with `-h`:
```
$ linode-cli linodes disks-list -h
usage: linode-cli [-h] [--label label] [--size size] linodeId

List Disks

positional arguments:
  linodeId

optional arguments:
  -h, --help     show this help message and exit
  --label label
  --size size
```
