### ISSUE TITLE
Brew Install fails because it can't get v1.41 of Scalar-List-Utils

### ISSUE THREAD

**Issue by phearlez** [linode/cli#38]
Seems like CPAN has stopped storing this version of Scalar-List-Utils; .42, .43 and .44 are the only ones listed in the cpan repo.

==> Downloading http://www.cpan.org/authors/id/P/PE/PEVANS/Scalar-List-Utils-1.41.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "linode-cli--Scalar::List::Utils"
Download failed: http://www.cpan.org/authors/id/P/PE/PEVANS/Scalar-List-Utils-1.41.tar.gz

**Comment by jamesottinger** [comment]
@phearlez, thank you for reporting! The brew formula was updated and the issue should now be resolved. Let me know if you have any further issues.
