### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by jooadam** [linode/cli#42]
jooadam@shulur:~$ time curl "https://api.linode.com?api_key=$key&api_action=avail.datacenters"
    
    ...
    
    real    0m0.767s
    user    0m0.016s
    sys     0m0.008s
    
    jooadam@shulur:~$ time linode locations
    
    ...
    
    real    0m3.615s
    user    0m0.996s
    sys     0m0.088s

Although support tries to convince me, I refuse to believe that parsing half a kilobyte of JSON and printing a single line per array item is justified to take nearly three seconds, hence I treat this as a bug.

Please let me know if additional information is needed.

**Comment by SirCmpwn** [comment]
That seems like a fair assessment, but tbh I don't think we'll be doing more than maintenance work on this repository right now. In the course of our work on [API 4](https://developers.linode.com) we've put together a new CLI.

Of course, patches welcome if you'd like to take a whack at improving this version.

**Comment by jooadam** [comment]
@SirCmpwn Okay, fair enough. I will keep using the Manager then, until v4 arrives.
