### ISSUE TITLE
Brew install fails

### ISSUE THREAD

**Issue by dky** [linode/cli#54]
Hello, all I'm getting the following when attempting to install via brew:

Already downloaded: /Users/dky/Library/Caches/Homebrew/linode-cli--JSON::PP-2.27203.tar.gz
==> perl Makefile.PL INSTALL_BASE=/usr/local/Cellar/linode-cli/1.4.7/libexec
==> make install
==> Downloading http://www.cpan.org/authors/id/E/EX/EXODIST/Test-Simple-1.302075.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "linode-cli--Test::Simple"
Download failed: http://www.cpan.org/authors/id/E/EX/EXODIST/Test-Simple-1.302075.tar.gz
dky@mba ~ $ brew tap linode/cli && brew install linode-cli^C

Looks like the version of Test-Simple has changed and the one being referenced no longer exist. How would we contribute a fix to this?

**Comment by dky** [comment]
I'm attempting to fix this error with the following pull request:

https://github.com/linode/homebrew-cli/pull/14

**Comment by jamesottinger** [comment]
https://github.com/linode/homebrew-cli/pull/14 was merged, which closes this issue. Thank you @dky for contributing!

**Comment by illblew** [comment]
Thanks @jamesottinger and @dky!
