### ISSUE TITLE
REQUEST: clone a linode

### ISSUE THREAD

**Issue by applelight** [linode/cli#56]
Would need a Linode cli command to help cloning a complete server. It's currently possible to do it from the web interface, and we should be able to do the same from cli.

ex:
$linode clone <source_linode> <destination_linode> <linode_datacenter> <linode_plan>

Regards.

**Comment by displague** [comment]
Thanks for reporting this @applelight and @1it.

This cli is deprecated in favor of https://github.com/linode/linode-cli (`pip install linode-cli`) which offers a `linode-cli linodes clone` option:

```bash
$ linode-cli linodes clone --help
linode-cli linodes clone [LINODEID]
Clone Linode

Arguments:
  --region: This is the Region where the Linode will be deployed.
  --type: A Linode's Type determines what resources are available toit, including disk space, memory, and virtual cpus.
  --linode_id: If an existing Linode is to be the target for the clone, the ID of that Linode.
  --label: The label to assign this Linode when cloning to a new Linode.
  --group: A label used to group Linodes for display.
  --backups_enabled: If this field is set to `true`, the created Linode willautomatically be enrolled in the Linode Backup service.
  --disks: All disks attached to configs will be cloned from the source Linode if not provided.
  --configs: All configs attached to will be cloned from the source Linode if not provided.
```

There are many more features available for Linodes and all Linode resource types in the new cli tool.  Here's a listing of the commands available for Linode instances alone:

| action              | summary                      |
 | --- | --- | 
| list                | List Linodes                 |
| create              | Create Linode                |
| view                | View Linode                  |
| update              | Update Linode                |
| delete              | Delete Linode                |
| backups-list        | List Backups                 |
| snapshot            | Create Snapshot              |
| backups-cancel      | Cancel Backups               |
| backups-enable      | Enable Backups               |
| backup-view         | View Backup                  |
| backup-restore      | Restore Backup               |
| boot                | Boot Linode                  |
| **clone**               | **Clone Linode**                 |
| configs-list        | List Configuration Profiles  |
| config-create       | Create Configuration Profile |
| config-view         | View Configuration Profile   |
| config-update       | Update Configuration Profile |
| config-delete       | Delete Configuration Profile |
| disks-list          | List Disks                   |
| disk-create         | Create Disk                  |
| disk-view           | View Disk                    |
| disk-update         | Update Disk                  |
| disk-delete         | Delete Disk                  |
| disk-reset-password | Reset Disk Root Password     |
| disk-resize         | Resize Disk                  |
| ips-list            | List Networking Information  |
| ip-add              | Allocate IPv4 Address        |
| ip-view             | View IP Address              |
| ip-update           | Update IP Address            |
| ip-delete           | Delete IPv4 Address          |
| migrate             | Initiate Pending Migration   |
| upgrade             | Upgrade Linode               |
| reboot              | Reboot Linode                |
| rebuild             | Rebuild Linode               |
| rescue              | Boot Linode into Rescue Mode |
| resize              | Resize Linode                |
| shutdown            | Shut Down Linode             |
| volumes             | List Linode's Volumes        |
| types               | List Types                   |
| type-view           | View Type                    |


Closes #52
