### ISSUE TITLE
Is it possible to update the main domain's IP using the CLI?

### ISSUE THREAD

**Issue by arpadlukacs** [linode/cli#57]
I could not figure out how to update the IP where the domain points. The command requires the -m param but the hostname is blank for that.

Eg it looks like that in the DNS manager:

![screenshot from 2017-05-13 10-19-34](https://cloud.githubusercontent.com/assets/557622/26023851/d0428f5e-37c5-11e7-8ba8-6cc2f0b23aa0.png)

The same domain looks like that using the CLI:

![screenshot from 2017-05-13 10-21-18](https://cloud.githubusercontent.com/assets/557622/26023860/04715b0c-37c6-11e7-8960-3c51ce0fc972.png)

I try to update the IP with the following command:

```
linode-domain -a record-update -l my-domain.com -t A -R'[remote_addr]'
```
but that throws the "The 'record-update' command requires a --match parameter." error.
I do not know what should I put after the -m param in that case. I tried everything I could come up. 
For subdomain "-m subdomain" works, but what if I do not want to update a subdomain?
I would like to have a domain pointed to my local machine for testing purposes.

**Comment by felicianotech** [comment]
Have you tried using `@`?

**Comment by arpadlukacs** [comment]
Yes, I did and did not work. I figured I need to use the "update" action instead of the record-update to change the main IP, so I need to update the domain itself, instead of a domain record. That is somewhat confusing, because the Linode admin page list them at the same place, so you would think you could manage them the same way via the CLI too. I guess, the issue can be closed.

**Comment by displague** [comment]
Thanks for reporting this, @arpadlukacs

This CLI tools is deprecated in favor of https://www.github.com/linode/linode-cli (`pip install linode-cli`) which is based on v4 of the Linode API.  It offers more commands and flexibility with a very similar interface.

For example, updating a domain record on the bare domain with the new CLI could be accomplished with:

```
$ linode-cli domains records-update --type A --name "" --target 1.2.3.4 $DOMAIN_ID $RECORD_ID

┌───────────┬──────┬──────┬─────────┬─────────┬──────────┬────────┐
│ id        │ type │ name │ target  │ ttl_sec │ priority │ weight │
├───────────┼──────┼──────┼─────────┼─────────┼──────────┼────────┤
│ RECORD_ID │ A    │      │ 1.2.3.4 │ 0       │ 0        │ 0      │
└───────────┴──────┴──────┴─────────┴─────────┴──────────┴────────┘
```

(I replaced the actual record_id with `RECORD_ID`)
