### ISSUE TITLE
CentOS 7 is missing

### ISSUE THREAD

**Issue by gaoyifan** [linode/cli#63]
I created a vm with CentOS 7 system, but a CentOS 6 was installed actually.

```
linode linode create -l xxx -L xxx -d 'CentOS 7' -p 'Linode 1024' -K ~/.ssh/id_rsa.pub -P xxx
```

**Comment by jamesottinger** [comment]
@gaoyifan, I was unable to duplicate this. Are you running this directly in a terminal? Perhaps something is happening to the quotes in your environment?

Here is what I ran:
$ linode  create -l "centos7" -L "newark" -d "Centos 7" -p "Linode 1024" -P "xxxx"

# cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)

**Comment by gaoyifan** [comment]
@jamesottinger  Thanks for your help.  I tried to re-run the same script just now, it indeed created a CentOS 7 VPS. 
I'll post further reports if it happens again.  Sorry for bothering you.

**Comment by jamesottinger** [comment]
@gaoyifan, great! Thanks for the update. 👍  We are always happy to help.
