### ISSUE TITLE
apt error buster debian

### ISSUE THREAD

**Issue by ghost** [linode/cli#68]
got this error in debian testing

apt update
W: GPG error: http://apt-longview.linode.com buster InRelease: The following signatures were invalid: D12F8D2C47B4A16917C9A040BED67E64325A043E
E: The repository 'http://apt-longview.linode.com buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by displague** [comment]
Thanks for reporting this @ghost.

This API v3 based CLI is deprecated in favor of the Linode API v4 based CLI at https://www.github.com/linode/linode-cli (`pip install linode-cli`).

We are not currently planning to add the new linode-cli to our APT repository, but I have created an issue to follow that topic: https://github.com/linode/linode-cli/issues/65
