### ISSUE TITLE
Failed to download resource

### ISSUE THREAD

**Issue by QNester** [linode/cli#69]
I run `brew install linode/cli/linode-cli` in terminal in my OS X 10.13 and have error:

```curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "linode-cli--Test::Simple"
Download failed: http://www.cpan.org/authors/id/E/EX/EXODIST/Test-Simple-1.302106.tar.gz
```

How can I fix it?

**Comment by jamesottinger** [comment]
@QNester, thank you for reporting the issue. I have updated the brew formula to address the failed download. If you refresh your formula, it should work. Let me know how you make out.
