### ISSUE TITLE
Cant verify SSL peers

### ISSUE THREAD

**Issue by QNester** [linode/cli#70]
I installed cli with "tar.gz method"
I set LINODE_API_KEY environment variable with generated api key, but I have error when i trying `linode list' or other commands:

```API unavailable: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust```

How can I fix it?

**Comment by displague** [comment]
Thanks for reporting this @QNester .

This API v3 based CLI is deprecated in favor of the Linode API v4 based CLI at https://www.github.com/linode/linode-cli (`pip install linode-cli`).
