### ISSUE TITLE
Linode IP configuration missing (IP failover/sharing and attachment)

### ISSUE THREAD

**Issue by eljoest** [linode/cli#71]
The CLI does not seem to have a way to configure IP attachments to a linode.
It doesn't seem possible to configure IP sharing/failover and attachment as documented in https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/ips/sharing and https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/ips/$ip_address

It would be quite nice for automating deployment to be able to configure this. Otherwise it's always necessary to do this step manually before a keepalived-type failover can be used.

**Comment by displague** [comment]
Thanks for reporting this, @eljoest 

This cli is deprecated in favor of https://github.com/linode/linode-cli (`pip install linode-cli`) which offers the commands you are looking for:

`linode-cli networking`

| action    | summary                |
|---|---|
| ips-list  | List IP Addresses      |
| ip-add    | Allocate IP Address    |
| ip-view   | View IP Address        |
| ip-update | Update IP Address RDNS |
| ip-assign | Assign IPs to Linodes  |
| ip-share  | Configure IP Sharing   |
| v6-pools  | List IPv6 Pools        |
| v6-ranges | List IPv6 Ranges       |
