### ISSUE TITLE
Brew Install fails because it can't get v1.47 of Scalar-List-Utils

### ISSUE THREAD

**Issue by attila** [linode/cli#73]
It looks like the problem that was fixed in https://github.com/linode/cli/issues/38 has struck again, this time 1.47 isn't available anymore, only 1.48, 1.49 and 1.50 😞 

```bash
==> Downloading http://www.cpan.org/authors/id/P/PE/PEVANS/Scalar-List-Utils-1.47.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "linode-cli--Scalar::List::Utils"
Download failed: http://www.cpan.org/authors/id/P/PE/PEVANS/Scalar-List-Utils-1.47.tar.gz
```

**Comment by jamesottinger** [comment]
@attila, thank you for reporting. The brew formula was updated to address this. The issue should be resolved. Let us know if you have any further issues.
